final List<Map<String, dynamic>> foodDB = [
  {"keyword": "rice", "name": "Cơm trắng", "cal": 130},
  {"keyword": "fried rice", "name": "Cơm chiên", "cal": 165},
  {"keyword": "sticky rice", "name": "Xôi", "cal": 217},
  {"keyword": "porridge", "name": "Cháo trắng", "cal": 70},
  {"keyword": "pho", "name": "Phở bò", "cal": 158},
  {"keyword": "pho chicken", "name": "Phở gà", "cal": 145},
  {"keyword": "bun bo", "name": "Bún bò Huế", "cal": 150},
  {"keyword": "bun rieu", "name": "Bún riêu", "cal": 120},
  {"keyword": "bun thit nuong", "name": "Bún thịt nướng", "cal": 190},
  {"keyword": "bun cha", "name": "Bún chả", "cal": 210},
  {"keyword": "banh mi", "name": "Bánh mì", "cal": 265},
  {"keyword": "bread", "name": "Bánh mì trắng", "cal": 265},
  {"keyword": "noodle", "name": "Mì gói", "cal": 470},
  {"keyword": "egg noodle", "name": "Mì trứng", "cal": 138},
  {"keyword": "spaghetti", "name": "Mì Ý", "cal": 158},
  {"keyword": "pasta", "name": "Pasta", "cal": 131},
  {"keyword": "pizza", "name": "Pizza", "cal": 266},
  {"keyword": "hamburger", "name": "Hamburger", "cal": 295},
  {"keyword": "hotdog", "name": "Hotdog", "cal": 290},
  {"keyword": "fried chicken", "name": "Gà rán", "cal": 260},
  {"keyword": "chicken", "name": "Thịt gà", "cal": 239},
  {"keyword": "beef", "name": "Thịt bò", "cal": 250},
  {"keyword": "pork", "name": "Thịt heo", "cal": 242},
  {"keyword": "fish", "name": "Cá", "cal": 206},
  {"keyword": "salmon", "name": "Cá hồi", "cal": 208},
  {"keyword": "tuna", "name": "Cá ngừ", "cal": 132},
  {"keyword": "shrimp", "name": "Tôm", "cal": 99},
  {"keyword": "crab", "name": "Cua", "cal": 97},
  {"keyword": "egg", "name": "Trứng gà", "cal": 155},
  {"keyword": "beef stew", "name": "Bò kho", "cal": 175},
  {"keyword": "pork stew", "name": "Thịt kho", "cal": 190},
  {"keyword": "fish sauce pork", "name": "Thịt kho tiêu", "cal": 210},
  {"keyword": "spring roll", "name": "Gỏi cuốn", "cal": 96},
  {"keyword": "fried spring roll", "name": "Chả giò", "cal": 154},
  {"keyword": "banh xeo", "name": "Bánh xèo", "cal": 215},
  {"keyword": "banh cuon", "name": "Bánh cuốn", "cal": 155},
  {"keyword": "banh bao", "name": "Bánh bao", "cal": 225},
  {"keyword": "banh chung", "name": "Bánh chưng", "cal": 170},
  {"keyword": "banh tet", "name": "Bánh tét", "cal": 200},
  {"keyword": "sushi", "name": "Sushi", "cal": 143},
  {"keyword": "sashimi", "name": "Sashimi", "cal": 121},
  {"keyword": "tempura", "name": "Tempura", "cal": 200},
  {"keyword": "udon", "name": "Udon", "cal": 105},
  {"keyword": "ramen", "name": "Ramen", "cal": 436},
  {"keyword": "tofu", "name": "Đậu hũ", "cal": 76},
  {"keyword": "tofu fried", "name": "Đậu hũ chiên", "cal": 270},
  {"keyword": "soy milk", "name": "Sữa đậu nành", "cal": 54},
  {"keyword": "milk", "name": "Sữa bò", "cal": 42},
  {"keyword": "yogurt", "name": "Sữa chua", "cal": 99},
  {"keyword": "che", "name": "Chè", "cal": 160},
  {"keyword": "ice cream", "name": "Kem", "cal": 207},
  {"keyword": "cake", "name": "Bánh kem", "cal": 257},
  {"keyword": "cookie", "name": "Bánh quy", "cal": 502},
  {"keyword": "chips", "name": "Khoai tây chiên lát", "cal": 536},
  {"keyword": "french fries", "name": "Khoai tây chiên", "cal": 312},
  {"keyword": "potato", "name": "Khoai tây luộc", "cal": 87},
  {"keyword": "sweet potato", "name": "Khoai lang", "cal": 86},
  {"keyword": "taro", "name": "Khoai môn", "cal": 142},
  {"keyword": "corn", "name": "Ngô", "cal": 96},
  {"keyword": "banana", "name": "Chuối", "cal": 89},
  {"keyword": "apple", "name": "Táo", "cal": 52},
  {"keyword": "orange", "name": "Cam", "cal": 47},
  {"keyword": "lemon", "name": "Chanh", "cal": 29},
  {"keyword": "grape", "name": "Nho", "cal": 57},
  {"keyword": "watermelon", "name": "Dưa hấu", "cal": 30},
  {"keyword": "melon", "name": "Dưa lưới", "cal": 34},
  {"keyword": "pear", "name": "Lê", "cal": 57},
  {"keyword": "peach", "name": "Đào", "cal": 39},
  {"keyword": "plum", "name": "Mận", "cal": 46},
  {"keyword": "mango", "name": "Xoài", "cal": 60},
  {"keyword": "papaya", "name": "Đu đủ", "cal": 43},
  {"keyword": "avocado", "name": "Bơ", "cal": 160},
  {"keyword": "pineapple", "name": "Dứa", "cal": 50},
  {"keyword": "coconut", "name": "Dừa", "cal": 354},
  {"keyword": "lettuce", "name": "Xà lách", "cal": 15},
  {"keyword": "cabbage", "name": "Bắp cải", "cal": 25},
  {"keyword": "carrot", "name": "Cà rốt", "cal": 41},
  {"keyword": "spinach", "name": "Rau chân vịt", "cal": 23},
  {"keyword": "morning glory", "name": "Rau muống", "cal": 18},
  {"keyword": "bok choy", "name": "Cải thìa", "cal": 13},
  {"keyword": "broccoli", "name": "Bông cải xanh", "cal": 34},
  {"keyword": "cauliflower", "name": "Súp lơ", "cal": 25},
  {"keyword": "tomato", "name": "Cà chua", "cal": 18},
  {"keyword": "onion", "name": "Hành tây", "cal": 40},
  {"keyword": "garlic", "name": "Tỏi", "cal": 149},
  {"keyword": "ginger", "name": "Gừng", "cal": 80},
  {"keyword": "mushroom", "name": "Nấm", "cal": 22},
  {"keyword": "oats", "name": "Yến mạch", "cal": 389},
  {"keyword": "peanut", "name": "Đậu phộng", "cal": 567},
  {"keyword": "almond", "name": "Hạnh nhân", "cal": 579},
  {"keyword": "walnut", "name": "Óc chó", "cal": 654},
  {"keyword": "cashew", "name": "Hạt điều", "cal": 553},
  {"keyword": "sesame", "name": "Mè", "cal": 573},
  {"keyword": "chia", "name": "Hạt chia", "cal": 486},
  {"keyword": "beef noodle soup", "name": "Mì bò", "cal": 190},
  {"keyword": "chicken noodle soup", "name": "Mì gà", "cal": 165},
  {"keyword": "dumpling", "name": "Há cảo", "cal": 220},
  {"keyword": "wonton", "name": "Hoành thánh", "cal": 240},
  {"keyword": "fried egg", "name": "Trứng chiên", "cal": 196},
  {"keyword": "boiled egg", "name": "Trứng luộc", "cal": 155},

  {"keyword": "omelette", "name": "Ốp la", "cal": 240},
  {"keyword": "sausage", "name": "Xúc xích", "cal": 301},
  {"keyword": "cheese", "name": "Phô mai", "cal": 402},
  {"keyword": "butter", "name": "Bơ", "cal": 717},
  {"keyword": "yoghurt", "name": "Sữa chua", "cal": 100},
  {"keyword": "bacon", "name": "Thịt xông khói", "cal": 541},
  {"keyword": "salad", "name": "Salad rau", "cal": 70},
  {"keyword": "fruit salad", "name": "Salad trái cây", "cal": 95},
  {"keyword": "fried fish", "name": "Cá chiên", "cal": 200},
  {"keyword": "boiled fish", "name": "Cá hấp", "cal": 116},
  {"keyword": "steamed shrimp", "name": "Tôm hấp", "cal": 84},
  {"keyword": "grilled pork", "name": "Heo nướng", "cal": 291},
  {"keyword": "grilled chicken", "name": "Gà nướng", "cal": 239},
  {"keyword": "fried pork", "name": "Thịt heo chiên", "cal": 350},
  {"keyword": "chili chicken", "name": "Gà xào ớt", "cal": 210},
  {"keyword": "curry chicken", "name": "Gà cà ri", "cal": 185},
  {"keyword": "curry beef", "name": "Bò cà ri", "cal": 210},
  {"keyword": "curry", "name": "Cà ri", "cal": 150},
  {"keyword": "fishcake", "name": "Chả cá", "cal": 110},
  {"keyword": "meatball", "name": "Xíu mại", "cal": 176},
  {"keyword": "pate", "name": "Pate", "cal": 319},
  {"keyword": "fried tofu", "name": "Đậu hũ chiên", "cal": 270},
  {"keyword": "soup", "name": "Canh rau", "cal": 40},
  {"keyword": "vegetable soup", "name": "Canh rau củ", "cal": 35},
  {"keyword": "chicken soup", "name": "Canh gà", "cal": 65},
  {"keyword": "beef soup", "name": "Canh bò", "cal": 95},
  {"keyword": "pumpkin soup", "name": "Canh bí đỏ", "cal": 52},
  {"keyword": "fish soup", "name": "Canh cá", "cal": 70},
  {"keyword": "salted egg", "name": "Trứng muối", "cal": 180},
  {"keyword": "quail egg", "name": "Trứng cút", "cal": 158},
  {"keyword": "clam", "name": "Nghêu", "cal": 74},
  {"keyword": "oyster", "name": "Hàu", "cal": 81},
  {"keyword": "snail", "name": "Ốc", "cal": 90},
  {"keyword": "squid", "name": "Mực", "cal": 175},
  {"keyword": "breaded shrimp", "name": "Tôm tẩm bột", "cal": 250},
  {"keyword": "fried squid", "name": "Mực chiên", "cal": 290},
  {"keyword": "grilled squid", "name": "Mực nướng", "cal": 158},
  {"keyword": "BBQ", "name": "BBQ", "cal": 270},
  {"keyword": "stew", "name": "Hầm", "cal": 160},
  {"keyword": "saigon bread", "name": "Bánh mì Sài Gòn", "cal": 270},
  {"keyword": "clam soup", "name": "Canh nghêu", "cal": 75},
  {"keyword": "duck", "name": "Thịt vịt", "cal": 337},
  {"keyword": "goose", "name": "Thịt ngỗng", "cal": 305},
  {"keyword": "turkey", "name": "Gà tây", "cal": 189},
  {"keyword": "pork rib", "name": "Sườn heo", "cal": 290},
  {"keyword": "beef rib", "name": "Sườn bò", "cal": 280},
];